#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\Home\HomeController::index
    methods: [GET]

about_us:
    path: /about_us
    controller: App\Controller\AboutUs\AboutUsController::index
    methods: [GET]

contact:
    path: /contact
    controller: App\Controller\Contact\ContactController::index
    methods: [GET]

news:
    path: /news
    controller: App\Controller\News\NewsController::index
    methods: [GET]

#health_check:
#  path: /
#  controller: App\Controller\HealthCheckController
#  methods: [ GET ]
